---
- name: "PHP | Add ondrej/ppa repository"
  apt_repository:
    repo: "ppa:ondrej/php"
- name: "PHP | Install php{{ php_version }}"
  apt:
    update_cache: yes
    name: 
      - libapache2-mod-php{{ php_version }}
      - php{{ php_version }}
      - php{{ php_version }}-bcmath
      - php{{ php_version }}-cli
      - php{{ php_version }}-curl
      - php{{ php_version }}-dev
      - php{{ php_version }}-fpm
      - php{{ php_version }}-gd
      - php{{ php_version }}-gmp
      - php{{ php_version }}-intl
      - php{{ php_version }}-json
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-memcached
      - php{{ php_version }}-mysql
      - php{{ php_version }}-readline
      - php{{ php_version }}-redis
      - php{{ php_version }}-xml
      - php{{ php_version }}-zip
      - php{{ php_version }}-memcache
    state: present
- name: PHP | Install composer
  shell: |
    curl -sS https://getcomposer.org/installer | php
    mv composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer
- name: Apache2 | Override php-fpm global pool configuration
  template:
    src: "pool.d/custom.conf.j2"
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    backup: yes
  notify: php-fpm restart
