---
- name: MySQL | Install MySQL
  apt:
    name: 
      - mysql-server
      - python-mysqldb
    state: present
- name: MySQL | Define root password
  mysql_user:
    check_implicit_admin: true
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    host: localhost
    password: "{{ mysql_root_password }}"
- name: MySQL | Remove anonymous user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: ""
    state: absent
- name: MySQL | Remove test database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: test
    state: absent
- name: "MySQL | Create {{ mysql_db }} database"
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: "{{ mysql_db }}"
    state: present
- name: "MySQL | Create {{ mysql_user }} user"
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: localhost
    priv: "{{ mysql_db }}.*:ALL"
    state: present